/**
 * Mock data for Files & Drawings Library - used when API is not available
 */

import type { LibraryFile, FileVersion } from '@/types/files-library'

export const mockLibraryFiles: LibraryFile[] = [
  {
    id: 'file-1',
    name: 'floor-plan-v2.pdf',
    type: 'drawing',
    size: 2457600,
    mimeType: 'application/pdf',
    currentVersionId: 'ver-1-2',
    uploadedBy: 'user-1',
    uploadedByName: 'Alex Morgan',
    uploadedAt: '2025-02-18T10:00:00Z',
    projectId: 'proj-1',
    isDeleted: false,
    previewUrl: '/files/floor-plan-v2-thumb.png',
    cdnUrl: '/files/floor-plan-v2.pdf',
    version: 2,
    linkedDecisionsCount: 1,
    linkedDecisions: [
      {
        id: 'att-1',
        decisionId: 'dec-3',
        decisionTitle: 'Floor Plan Revision - Master Suite',
        fileId: 'file-1',
        attachedAt: '2025-02-18T10:30:00Z',
        attachmentType: 'primary',
      },
    ],
  },
  {
    id: 'file-2',
    name: 'countertop-specs.pdf',
    type: 'spec',
    size: 512000,
    mimeType: 'application/pdf',
    currentVersionId: 'ver-2-1',
    uploadedBy: 'user-2',
    uploadedByName: 'Sarah Chen',
    uploadedAt: '2025-02-15T09:30:00Z',
    projectId: 'proj-1',
    isDeleted: false,
    previewUrl: '/files/countertop-specs-thumb.png',
    cdnUrl: '/files/countertop-specs.pdf',
    version: 1,
    linkedDecisionsCount: 1,
    linkedDecisions: [
      {
        id: 'att-2',
        decisionId: 'dec-1',
        decisionTitle: 'Kitchen Finishes - Countertops',
        fileId: 'file-2',
        attachedAt: '2025-02-15T10:00:00Z',
        attachmentType: 'primary',
      },
    ],
  },
  {
    id: 'file-3',
    name: 'exterior-render.png',
    type: 'image',
    size: 1024000,
    mimeType: 'image/png',
    currentVersionId: 'ver-3-1',
    uploadedBy: 'user-1',
    uploadedByName: 'Alex Morgan',
    uploadedAt: '2025-02-10T14:00:00Z',
    projectId: 'proj-1',
    isDeleted: false,
    previewUrl: '/files/exterior-render.png',
    cdnUrl: '/files/exterior-render.png',
    version: 1,
    linkedDecisionsCount: 1,
    linkedDecisions: [
      {
        id: 'att-3',
        decisionId: 'dec-2',
        decisionTitle: 'Exterior Paint Color',
        fileId: 'file-3',
        attachedAt: '2025-02-10T15:00:00Z',
        attachmentType: 'primary',
      },
    ],
  },
  {
    id: 'file-4',
    name: 'structural-model.rvt',
    type: 'BIM',
    size: 15728640,
    mimeType: 'application/octet-stream',
    currentVersionId: 'ver-4-1',
    uploadedBy: 'user-1',
    uploadedByName: 'Alex Morgan',
    uploadedAt: '2025-02-12T11:00:00Z',
    projectId: 'proj-1',
    isDeleted: false,
    previewUrl: null,
    cdnUrl: '/files/structural-model.rvt',
    version: 1,
    linkedDecisionsCount: 0,
    linkedDecisions: [],
  },
]

export const mockFileVersions: Record<string, FileVersion[]> = {
  'file-1': [
    {
      id: 'ver-1-2',
      fileId: 'file-1',
      versionNumber: 2,
      createdAt: '2025-02-18T10:00:00Z',
      uploaderId: 'user-1',
      uploaderName: 'Alex Morgan',
      notes: 'Updated floor plan with master suite revisions',
      assetUrl: '/files/floor-plan-v2.pdf',
      previewUrl: '/files/floor-plan-v2-thumb.png',
      size: 2457600,
    },
    {
      id: 'ver-1-1',
      fileId: 'file-1',
      versionNumber: 1,
      createdAt: '2025-02-10T09:00:00Z',
      uploaderId: 'user-1',
      uploaderName: 'Alex Morgan',
      notes: 'Initial floor plan upload',
      assetUrl: '/files/floor-plan-v1.pdf',
      previewUrl: '/files/floor-plan-v1-thumb.png',
      size: 2300000,
    },
  ],
  'file-2': [
    {
      id: 'ver-2-1',
      fileId: 'file-2',
      versionNumber: 1,
      createdAt: '2025-02-15T09:30:00Z',
      uploaderId: 'user-2',
      uploaderName: 'Sarah Chen',
      notes: 'Countertop specifications document',
      assetUrl: '/files/countertop-specs.pdf',
      previewUrl: '/files/countertop-specs-thumb.png',
      size: 512000,
    },
  ],
  'file-3': [
    {
      id: 'ver-3-1',
      fileId: 'file-3',
      versionNumber: 1,
      createdAt: '2025-02-10T14:00:00Z',
      uploaderId: 'user-1',
      uploaderName: 'Alex Morgan',
      notes: 'Exterior render for paint selection',
      assetUrl: '/files/exterior-render.png',
      previewUrl: '/files/exterior-render.png',
      size: 1024000,
    },
  ],
  'file-4': [
    {
      id: 'ver-4-1',
      fileId: 'file-4',
      versionNumber: 1,
      createdAt: '2025-02-12T11:00:00Z',
      uploaderId: 'user-1',
      uploaderName: 'Alex Morgan',
      notes: 'Revit structural model - Autodesk Forge integration pending',
      assetUrl: '/files/structural-model.rvt',
      previewUrl: null,
      size: 15728640,
    },
  ],
}
